### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hemanth** [6to5/6to5-browser-extension#1]
- [ ] Ask @richgilbank if he wants to pump in some init code?

- [ ] Based on the result from the first item, decide further actions.

- [ ] Create chrome extension. ( Would be good if we use [generator-chrome-extension](https://github.com/yeoman/generator-chrome-extension))

- [ ] Create Firefox extension.

- [ ] Decide upon extensions for other browsers.

//cc @sebmck @thejameskyle

**Comment by stoeffel** [comment]
I would be happy to help :smile:

**Comment by richgilbank** [comment]
I'd be happy to help on this as well, but I'm not entirely sure what the real objective is here. What is it we'd want to build? If it's simply a console in DevTools that executes in the current page's context, it seems the easier path would just be to add a 6to5 option (as a new default even) to the [current project](https://github.com/richgilbank/ES6-Repl-Chrome-Extension), which I'd be in favour of doing (in fact, I may just get started on it :stuck_out_tongue:). 

Also, as I mentioned in the [previous thread](https://github.com/6to5/6to5/issues/618), there are currently some pretty significant issues with the FF Add-on SDK currently that basically prohibit this from happening yet (https://github.com/mdn/repl-panel/issues/2, https://github.com/mdn/repl-panel/issues/1 for example). 

Opera and Spartan are gimmes as they 'just work' with the Chrome API :sparkles:

Anyways, as I mentioned, I'd be happy to help, be it improving the existing one or creating something new here, just looking for some clarification on the goals.

**Comment by hemanth** [comment]
@richgilbank The whole idea is to have a `official` browser extension/plugin very much similar to ES6-Repl-Chrome-Extension, but here we could toggle transpiled code as well as execute it as is.

>be it improving the existing one or creating something new here

Creating something new here is the goal :tada:

**Comment by darcyclarke** [comment]
@hemanth This sounds counter-intuitive. There's already a [project](https://github.com/richgilbank/ES6-Repl-Chrome-Extension) that exists to fill this need. Why not work to add 6to5 support on @richgilbank's project? Or better yet, why not just ask him to add support? 

It honestly feels like you're trying to force a change in ownership of code without providing any inherit value in doing so. Your essentially saying, "Hey Rich, contribute your existing work or we're going to duplicate your efforts either way". Having an `official` extension doesn't seem like reason enough to create fragmentation. Actions like this only discourage new developers to contribute to open source communities and create new projects out of fear in being made irrelevant or ripped off when it's convenient or advantageous. No one can stop you from forking code but this doesn't sit well with me culture and community-wise.

I hope this kind of thing isn't supported by the rest of the 6to5 team. @sindresorhus & others feel free to chime in. My suggestion would be to open an issue on **ES6 Repl** or make a PR against that project for 6to5 support. 

**The enthusiasm is great to see but seems misguided.**

**Comment by sebmck** [comment]
@darcyclarke I green-lit this in 6to5/6to5#618. If @richgilbank is willing to add support for 6to5 to his existing extension then I see no need to for this repo/project to exist. I made it clear with @hemanth in our [gitter room](https://gitter.im/6to5/6to5). I jumped the gun a bit but allowing this repo to be created in the first place.

I hate [duplicate effort](6to5.org/blog/2015/01/12/6to5-esnext/) and don't think these things should be a collaborative effort, especially if there's multiple people interested. To be honest, I'm kind of skeptical of the inherent value in a browser extension at all as it doesn't offer anything more than the [REPL](http://6to5.org/repl/).

**Comment by darcyclarke** [comment]
@sebmck Agreed

**Comment by richgilbank** [comment]
Agreed all round, and I've already begun work on it.

**Comment by sebmck** [comment]
@richgilbank Great, I see no need to have this repo then. If you'd like to migrate your extension over at some stage to the org, feel free to let me know. I wont delete this repo as it'd be disingenuous to hide this kind of discussion. I'll point the README and repo URL to point to your repo. Thanks everyone!

**Comment by hemanth** [comment]
:+1: 

>The enthusiasm is great to see but seems misguided.

Sorry for that ^

Thank you all, thanks to @richgilbank specially :)
